# NUMPY:
* NumPy is a Python library.  
* NumPy is used for working with arrays.  
* NumPy is short for "Numerical Python".
* import numpy as np -this the formate to import

In [2]:
import numpy as np

In [4]:
a=np.array(2)
print(a)

2


In [7]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [8]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
print(np.__version__)                 #to findout a version of numpy

2.1.3



**types of arrays**

* 0-D Arrays
* 1-D Arrays
* 2-D Arrays-its perform row & column
* 3-D arrays -it follows layer,row,coloumn

In [13]:
# 0 dimens

import numpy as np
a = np.array(90)
print(a)
print(a.ndim)         #finding dimension
print(a.shape)

90
0
()


In [15]:
#1 dimension
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
[1 2 3 4 5]


In [16]:
#2 dimension
import numpy as np
b=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [17]:
#3 dimension
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,1]]])
print(a.ndim)
print(a)

3
[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 2 1]]]


# indexing

In [19]:
import numpy as np
a=np.array([1,2,3,5])
print(a[2])

3


In [20]:
#normal list
a=[1,2,3],[3,4,5],[6,9,8]
a[1][1]

4

In [58]:
#in numpy
n = np.array([[1,8],[5,9]])
print(n[1,0])
print(n.ndim)

5
2


In [5]:
b=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(b[2,1])
print(b.ndim)

7
2


In [6]:
i=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,2,1]]])         #[1 to 6] is= 0 na d next 7 to 1 is =1
print(i[1,1,2]) 
print(i[:])                  #[:] means full
print(i.ndim)

1
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 2 1]]]
3


In [7]:
arr = np.array([
                [[1,2,3],[4,5,6]],     
                [[7,8,9],[10,11,12]] 
              ])
print(arr[1,1,1])
#print(arr.shape)
print(arr.ndim)

11
3


# slicing:
*  We pass slice instead of index like this: [start:end].  
* We can also define the step, like this: [start:end:step].

In [77]:
import numpy as mp
s=np.array([1,2,3,4,5,6,7])
print(s[0:4])
print(s[:])

[1 2 3 4]
[1 2 3 4 5 6 7]


In [9]:
s1=np.array([1,2,3,4,5,6,7,8])
print(s1[-3:-1])

[6 7]


In [10]:
s1=np.array([1,2,3,4,5,6,7,8])
print(s1[:-1])
print(s1[::-1])      #1.:start   2.:end   3.: step

[1 2 3 4 5 6 7]
[8 7 6 5 4 3 2 1]


In [87]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:-1:2])

[1 3 5]


In [27]:
import numpy as np
d = np.array([[[1, 2, 3, 4, 5],[6,7,8,9,10]],[[11, 12, 13, 14, 15],[16,17,18,19,20]]])
print(d.ndim)
print(d[0,1,:]) # it gets 0th layer and 1st row of full column


3
[ 6  7  8  9 10]


In [22]:
b=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(b[2,1:2])
print(b.ndim)

[7]
2


In [25]:
a=[1,2,3,4]
print(str(a))

[1, 2, 3, 4]


In [50]:
#casting
a=np.array([1,2,3,4],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [54]:
a=np.array(["a","b","c"])
print(a.dtype)
print(a)

<U1
['a' 'b' 'c']


In [8]:
a = np.array(5)        # 0D
b = a.reshape(1,1,1)   # make it 3D
print(b)
print(b.shape)        # (1, 1, 1)


[[[5]]]
(1, 1, 1)


In [20]:
a=np.array([1,2,3,5])
b=a.reshape(1,4)
print(b)
print(b.ndim)
print(a.ndim)

[[1 2 3 5]]
2
1


In [29]:
b=np.array([[1,2,3],[4,5,6],[6,7,8]])
c=b.reshape(3,3,1)
print(c)
print(c.ndim)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[6]
  [7]
  [8]]]
3


In [55]:
#1-2d
#2-3d
#2,3-1
a=np.array([1,2,3,4,5,6,7,8,9])


In [30]:
import numpy as np
a=np.array([[1],[2]])
print(a[[0]])
print(a[0][0])

[[1]]
1


In [21]:
n=np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1]])
b=n.reshape(2,2,3)
print(b)             
print(b.ndim)            #2 = 3   

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 2 1]]]
3


In [26]:
n=np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1]])
b=n.reshape([12])
print(b)
print(b.ndim)           #2==1

[1 2 3 4 5 6 7 8 9 3 2 1]
1


In [30]:
d = np.array([[[1, 2, 3, 4, 5],[6,7,8,9,10]],[[11, 12, 13, 14, 15],[16,17,18,19,20]]])
d1=d.reshape([20])
print(d1.ndim)           # 3 to 1

1


In [32]:
d2=d.flatten()
d2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])