# data types
*  i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* S - string

In [2]:
import numpy as np
#a.dtype its a finding type of data in numpy

In [5]:
# integer
a = np.array([1, 2, 3, 4])
print(type(a))
print(a.dtype)
a

<class 'numpy.ndarray'>
int64


array([1, 2, 3, 4])

In [3]:
#unsigned
a = np.array(["ab","ju8","979kjui8yhi"])

print(a.dtype)
#U: Represents a Unicode string data type in NumPy.
#11: Indicates the maximum length of each string in the array, in terms of Unicode characters.

<U11


In [7]:
#float
a = np.array([2.7,9.0])
print(a.dtype)

float64


In [8]:
#complex
a=np.array([1+4j,2+2j])
print(a.dtype)

complex128


In [4]:
#string
s=np.array(["abi","abinesh"])
print(s.dtype)

<U7


In [27]:
#convert type
c=np.array([1,2,3,4,5],dtype='S')
print(c)
print(c.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [15]:
i=np.array([1,2,3,4,6,7],dtype='i8')         #i8 means mentioning the size of bit
print(i.dtype)                            
print(i)

int64
[1 2 3 4 6 7]


In [18]:
i=np.array([1,2,3,4,6,7],dtype='i4')         #i4 means mentioning the size of bit
print(i.dtype)                            
print(i)

int32
[1 2 3 4 6 7]


In [17]:
i=np.array([1,2,3,4,6,7],dtype='i2')         #i2 means mentioning the size of bit
print(i.dtype)                            
print(i)

int16
[1 2 3 4 6 7]


In [21]:
i=np.array([1,2,3,4,6,7],dtype='i')         #i8 means mentioning the size of bit
print(i.dtype)                            
print(i)

int32
[1 2 3 4 6 7]


In [25]:
a = np.array(['1', '2', '3'], dtype='i8')
print(a)
print(a.dtype)
print(a.astype)

[1 2 3]
int64
<built-in method astype of numpy.ndarray object at 0x0000021A8A973150>


In [35]:
#CASTING-astype
a=np.array(['1','2','3','4'])
b=a.astype(int)
print(b)
print(b.dtype)


[1 2 3 4]
int64


In [30]:
a=np.array([1,2,4])
b=a.astype('S')
print(b)
print(b.dtype)

[b'1' b'2' b'4']
|S21


In [34]:
a=np.array([1,2,3,4])
b=a.astype(float)
print(b)
print(b.dtype)

[1. 2. 3. 4.]
float64


In [33]:
a=np.array([1,0,2])
b=a.astype(bool)
print(b)
print(b.dtype)

[ True False  True]
bool


In [37]:
a = np.array(["1", "2", "3"])
b = a.astype("i4")
print(b)
print(b.dtype)

[1 2 3]
int32


# **copy:**
* to get a aditional of data like duplicate using copy
* its not affect original its only update the copied data

  

In [39]:
import numpy as np

a=np.array([1,2,3,5,8])
c=a.copy()
c[0]=10
print(a)
print(c)

[1 2 3 5 8]
[10  2  3  5  8]


# **view:**
* its used to if you change the data while programming and the original data also change

In [41]:
a=np.array([0,2,3,5,7])
v=a.view()
v[0]=1
v[4]=6
print(v)
print(a)

[1 2 3 5 6]
[1 2 3 5 6]


In [42]:
a=np.array([[1,2],[3,4],[6,7]])
b=[]
for i in np.nditer(a):
    b.append(int(i))
print(b)

[1, 2, 3, 4, 6, 7]


In [46]:
#MATH OPERATION
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4, 5, 6],[1, 2, 3]])
add=a+b
sub=a-b
mult=a*b
div=a/b
print("add",add)
print()
print("sub",sub)
print()
print("mult",mult)
print()
print("div",div)
#perform each element with another var each element their perform with pairs of operation

add [[5 7 9]
 [2 4 6]]

sub [[-3 -3 -3]
 [ 0  0  0]]

mult [[ 4 10 18]
 [ 1  4  9]]

div [[0.25 0.4  0.5 ]
 [1.   1.   1.  ]]


In [47]:
a=np.array([1,2,3])
b=np.array([4,5,6])
for i in range(len(a)):
    print(a[i]+b[i])
    

5
7
9


In [49]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a/b)
print(a*b)

[0.25 0.4  0.5 ]
[ 4 10 18]
